import 'package:teste_cubiq/business/entities/chat_entity.dart';

List<ChatEntity> chatsMock = [
  ChatEntity(
    name: 'Rosangela Neves',
    lastMesasage: 'Olá, como tu está?',
    imageUrl: 'images/avatar.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 5)),
    type: ChatType.unread,
  ),
  ChatEntity(
    name: 'Cassio Machado',
    lastMesasage: 'Oi, vamos nos encontrar amanhã?',
    imageUrl: 'images/avatar1.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 10)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Daniela Targaryen',
    lastMesasage: 'Você viu o último episódio?',
    imageUrl: 'images/avatar2.png',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 1)),
    type: ChatType.finished,
  ),
  ChatEntity(
    name: 'Samuel Tarly',
    lastMesasage: 'Sim, eu adorei!',
    imageUrl: 'images/avatar3.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 2)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Cersei Lannister',
    lastMesasage: 'Vamos marcar um café?',
    imageUrl: 'images/avatar4.png',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Arya Stark',
    lastMesasage: 'Qual o plano para hoje?',
    imageUrl: 'images/avatar5.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 2)),
    type: ChatType.unread,
  ),
  ChatEntity(
    name: 'Jorah Mormont',
    lastMesasage: 'Recebi suas fotos, estão ótimas!',
    imageUrl: 'images/avatar6.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 3)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Missandei',
    lastMesasage: 'Não esqueça nossa reunião amanhã.',
    imageUrl: 'images/avatar7.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 4)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Sansa Stark',
    lastMesasage: 'Bom dia! Como você está?',
    imageUrl: 'images/avatar8.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 5)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Ana Carolina',
    lastMesasage: 'Estou indo para a academia.',
    imageUrl: 'images/avatar9.png',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 30)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Guilherme',
    lastMesasage: 'Você já terminou aquele projeto?',
    imageUrl: 'images/avatar11.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 45)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Maria Solange',
    lastMesasage: 'Precisamos discutir o orçamento.',
    imageUrl: 'images/avatar.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 3)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Eddard Stark',
    lastMesasage: 'Obrigado pela ajuda!',
    imageUrl: 'images/avatar1.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 4)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Rosana',
    lastMesasage: 'Você está livre hoje à noite?',
    imageUrl: 'images/avatar4.png',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 6)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Maria Perci',
    lastMesasage: 'Vamos sair para jantar?',
    imageUrl: 'images/avatar5.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(days: 7)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Roberto Baratheon',
    lastMesasage: 'Tenho novidades para você!',
    imageUrl: 'images/avatar6.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(minutes: 15)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Marcia Zilles',
    lastMesasage: 'Vamos assistir um filme?',
    imageUrl: 'images/avatar7.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 5)),
    type: ChatType.read,
  ),
  ChatEntity(
    name: 'Sabrina Rosa',
    lastMesasage: 'Estou trabalhando no relatório.',
    imageUrl: 'images/avatar8.jpeg',
    lastMessageTime: DateTime.now().subtract(const Duration(hours: 6)),
    type: ChatType.read,
  ),
];

final messagesMock = [];
